name: "BookLore"
slug: "booklore"
version: "latest"
description: "Self-hosted book & comic library (PDF, EPUB, CBZ) with metadata, OPDS, multi-user, built-in reader."
url: "https://github.com/Tokahiro/ha-addons/tree/main/booklore"
arch: [aarch64, armv7, amd64]
startup: application

ingress: true
ingress_port: 6060
ingress_entry: "/"
panel_icon: "mdi:book-open-variant"
panel_title: "BookLore"

ports:
  "6060/tcp": null
ports_description:
  "6060/tcp": "Web UI (optional external access)"

# Map HA folders for your library & uploads
map:
  - type: media
    read_only: false
  - type: share
    read_only: false

apparmor: true
host_network: false
privileged: []

homeassistant: "2023.12.0"

# Reuse upstream BookLore image (multi-arch manifest)
image: "ghcr.io/adityachandelgit/booklore-app"

# Database env (manual, since we're reusing the upstream container)
environment:
  DATABASE_URL: "jdbc:mariadb://core-mariadb:3306/booklore"
  DATABASE_USERNAME: "booklore"
  DATABASE_PASSWORD: "CHANGE_ME"