name: "BookLore"
slug: "booklore"
version: "0.20.30"                 # add-on version (not the BookLore image tag)
description: "Self-hosted book & comic library with metadata, OPDS, multi-user and built-in reader."
url: "https://github.com/Tokahiro/ha-addons/tree/main/booklore"
arch:
  - aarch64
  - armv7
  - amd64
startup: application

# Ingress: visible in the HA sidebar, no extra host port needed
ingress: true
ingress_port: 6060
ingress_entry: "/"
panel_icon: "mdi:book-open-variant"
panel_title: "BookLore"

# Optional: expose host port in addition to Ingress (keep null to disable)
ports:
  "6060/tcp": 6060
ports_description:
  "6060/tcp": "Web UI (optional external access)"

# Map HA folders for libraries/uploads
map:
  - type: media
    read_only: false
  - type: share
    read_only: false

# Use the Services API for MariaDB auto-discovery
services:
  - "mysql:need"

# Security posture
apparmor: true
host_network: false
privileged:
  - SYS_ADMIN  # Required for mount operations
devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  # Note: Additional partitions can be added as needed

# Minimum HA version
homeassistant: "2023.12.0"

# --- Configuration tab (shown in Supervisor UI) ---
options:
  use_mysql_service: true
  db_host: "core-mariadb"     # Fallback host if not using discovery
  db_port: 3306
  db_name: "booklore"
  db_user: "booklore"
  db_password: "CHANGE_ME"
  swagger_enabled: false
  mounts: []  # List of device paths or labels
schema:
  use_mysql_service: bool
  db_host: str
  db_port: int
  db_name: str
  db_user: str
  db_password: password
  swagger_enabled: bool
  mounts:
    - "str?"